Repository cetz-package/cetz, pull requests merged in 2023-11, with the labels that each got.

#312 draw: Improve group & content padding
  src/aabb.typ
  src/draw/grouping.typ
  src/draw/shapes.typ
  src/styles.typ
  src/util.typ
  tests/content/padding/ref.png
  tests/content/padding/test.typ
  tests/group/padding/ref.png
  tests/group/padding/test.typ
Labels: enhancement :arrow_up:

#315 Fixed school book axis labels not respecting offset.
  src/lib/axes.typ
Labels: bug :bug:, lib:plot, lib:chart :chart:

#317 Add support for customising axis label anchor in school-book style
  src/lib/axes.typ
Labels: enhancement :arrow_up:, lib:plot

#323 gallery: Update cetz version
  .github/workflows/ci.yml
  gallery/3d-chart.typ
  gallery/barchart.typ
  gallery/karls-picture.typ
  gallery/pie-chart.typ
  gallery/plot.typ
  gallery/tree.typ
Labels: documentation

#319 Hobby Curve Implementation
  manual.typ
  src/complex.typ
  src/draw.typ
  src/draw/shapes.typ
  src/hobby.typ
  src/mark.typ
  src/styles.typ
  tests/hobby/ref.png
  tests/hobby/test.typ
  tests/mark/auto-offset/ref.png
  tests/mark/auto-offset/test.typ
  tests/mark/multiple/ref.png
  tests/mark/multiple/test.typ
Labels: feature :gift:, core:draw :pencil2:

#326 draw: Do not transform content anchors
  src/anchor.typ
  src/draw/shapes.typ
  tests/content/anchor/ref.png
  tests/content/anchor/test.typ
  tests/content/padding/test.typ
  tests/content/ref.png
  tests/content/rotate/ref.png
  tests/content/rotate/test.typ
  tests/content/transform/ref.png
  tests/content/transform/test.typ
  tests/helper.typ
  tests/intersection/ref.png
Labels: bug :bug:

#338 bezier: Improve cubic-t-for-distance
  src/bezier.typ
  src/path-util.typ
  tests/anchor-on-path/ref.png
  tests/bezier-through/ref.png
  tests/bezier/shorten/ref.png
  tests/mark/auto-offset/ref.png
  tests/mark/multiple/ref.png
  tests/mark/place-marks/ref.png
Labels: bug :bug:, enhancement :arrow_up:

#344 tests: Update ref image
  tests/content/transform/ref.png
Labels: question :grey_question:

#275 Make rotations/angles consistent
  src/draw/shapes.typ
  src/lib/angle.typ
  src/lib/axes.typ
  src/lib/decorations.typ
  src/vector.typ
  tests/axes/test.typ
  tests/content/ref.png
  tests/content/rotate/ref.png
Labels: bug :bug:

#355 Making `x-grid` great again
  src/lib/axes.typ
  tests/axes/ref.png
  tests/chart/ref.png
  tests/plot/ref.png
Labels: bug :bug:, lib:plot
