Repository cetz-package/cetz, pull requests merged in 2023-08, with the labels that each got.

#112 Convert all beziers to cubic ones
  bezier.typ
  cmd.typ
  draw.typ
  intersection.typ
  manual.pdf
  path-util.typ
  scripts/test
  tests/anchor-on-path/ref.png
  tests/bezier-through/ref.png
  tests/bezier-through/test.typ
  tests/intersection/ref.png
  tests/local-package/ref.png
  tests/marks/ref.png
  tests/merge/ref.png
  tests/primitives/ref.png
  tests/ring/ref.png
Labels: enhancement

#115 plot: Support functions returning vectors as data pts
  lib/plot.typ
  tests/plot/ref.png
  tests/plot/test.typ
Labels: enhancement

#118 Fix alignment
  canvas.typ
Labels: bug :bug:

#117 Fix debug
  canvas.typ
Labels: bug :bug:

#119 typst v0.7.0
  .github/workflows/ci.yml
  gallery/karls-picture.png
  gallery/plot.png
  scripts/package
  scripts/test
  tests/anchor-on-path/ref.png
  tests/arc/ref.png
  tests/arrows/ref.png
  tests/axes/ref.png
  tests/bezier-through/ref.png
  tests/chart/ref.png
  tests/circle-through/ref.png
  tests/circle/ref.png
  tests/cube/ref.png
  tests/grid/ref.png
  tests/image/ref.png
  tests/intersection/ref.png
  tests/local-anchor/ref.png
  tests/local-package/ref.png
  tests/marks/ref.png
  tests/merge/ref.png
  tests/plot/ref.png
  tests/primitives/ref.png
  tests/relative-length/ref.png
  tests/ring/ref.png
  tests/rotation/ref.png
  tests/shadow/ref.png
  tests/translation/ref.png
  tests/tree/ref.png
  tests/viewport/ref.png
Labels: enhancement

#120 scripts: Fix package location
  scripts/package
Labels: bug :bug:

#124 chart: Fix data/label order
  CHANGES.md
  gallery/3d-chart.typ
  gallery/barchart.typ
  gallery/karls-picture.png
  gallery/karls-picture.typ
  gallery/pie-chart.png
  gallery/pie-chart.typ
  gallery/plot.png
  gallery/plot.typ
  gallery/tree.typ
  lib/chart.typ
  tests/chart/ref.png
  tests/chart/test.typ
Labels: bug :bug:

#125 canvas: Calculate path aabb using path-util.bounds
  CHANGES.md
  canvas.typ
  cmd.typ
  manual.pdf
  tests/bounds/ref.png
  tests/bounds/test.typ
  tests/intersection/ref.png
Labels: bug :bug:, enhancement

#128 doc: Use same source for drawing and example codec
  manual.pdf
  manual.typ
Labels: documentation, enhancement

#134 Allow negative tick direction for scientific and left plots
  gallery/barchart.png
  gallery/plot.png
  manual.pdf
  manual.typ
  src/lib/axes.typ
  src/lib/plot.typ
  tests/axes/ref.png
  tests/axes/test.typ
Labels: bug :bug:, enhancement

#135 Support tick label rotation
  manual.pdf
  src/lib/axes.typ
  tests/axes/ref.png
  tests/axes/test.typ
Labels: enhancement

#140 Bezier Marks
  manual.pdf
  manual.typ
  src/draw.typ
  src/styles.typ
  tests/bezier-through/ref.png
  tests/bezier-through/test.typ
Labels: documentation, enhancement

#141 Add angle library
  CHANGES.md
  manual.pdf
  manual.typ
  src/bezier.typ
  src/canvas.typ
  src/cmd.typ
  src/draw.typ
  src/lib.typ
  src/lib/angle.typ
  src/styles.typ
  tests/angle/ref.png
  tests/angle/test.typ
  tests/merge/ref.png
  tests/ring/ref.png
Labels: enhancement

#146 readme: Update projects using CeTZ
  README.md
Labels: documentation
