Repository cetz-package/cetz, pull requests merged in 2023-06, with the labels that each got.

#54 Add padding around content blocks
  canvas.typ
  draw.typ
Labels: enhancement

#55 Various fixes and additions
  canvas.typ
  draw.typ
  matrix.typ
  vector.typ
Labels: bug, enhancement

#61 The arc command is updated.
  cmd.typ
  draw.typ
  manual.pdf
  manual.typ
  tests/local-anchor/test.typ
  tests/primitives/test.typ
  tests/ring/test.typ
Labels: enhancement

#68 Document Groups and Transforms
  draw.typ
  manual.pdf
  manual.typ
  matrix.typ
Labels: documentation

#65 Refactor the Path Command
  canvas.typ
  cmd.typ
  draw.typ
  path-util.typ
  tests/anchor-on-path/ref.png
  tests/anchor-on-path/test.typ
  tests/arrows/ref.png
  tests/axes/ref.png
  tests/grid/ref.png
  tests/grid/test.typ
  tests/image/ref.png
  tests/local-anchor/ref.png
  tests/marks/ref.png
  tests/marks/test.typ
  tests/merge/ref.png
  tests/merge/test.typ
  tests/primitives/ref.png
  tests/ring/test.typ
  tests/rotation/ref.png
  tests/run
  tests/translation/ref.png
  util.typ
  vector.typ
Labels: enhancement

#60 Add generalised styling function
  canvas.typ
  cmd.typ
  draw.typ
  manual.pdf
  manual.typ
  styles.typ
  tests/arrows/test.typ
  tests/axes/test.typ
  tests/circle/test.typ
  tests/image/test.typ
  util.typ
Labels: enhancement
