Repository cetz-package/cetz, pull requests merged in 2023-09, with the labels that each got.

#152 content: Add option to span content between coordinates
  CHANGES.md
  manual.pdf
  manual.typ
  src/canvas.typ
  src/draw.typ
  src/styles.typ
  tests/content/ref.png
  tests/content/test.typ
Labels: feature :gift:

#153 content: Fixup
  CHANGES.md
  manual.pdf
  src/draw.typ
Labels: documentation

#154 ci: Use gnu-parallel if available
  .github/workflows/ci.yml
  scripts/test
Labels: enhancement

#158 pkg: Add keywords
  typst.toml
Labels: documentation

#159 cmd: Fix missing ellipse z coordinate
  src/cmd.typ
  tests/circle/ref.png
  tests/circle/test.typ
Labels: bug :bug:

#160 draw: Add get-/set-ctx functions
  manual.pdf
  manual.typ
  src/draw.typ
  tests/set-get-ctx/ref.png
  tests/set-get-ctx/test.typ
Labels: enhancement

#171 draw: Fix content angle coordinate check
  src/draw.typ
  tests/content/ref.png
  tests/content/test.typ
Labels: bug :bug:

#175 plot: Add sample-at option to `add(..)` for adding sampling points
  manual.pdf
  src/lib/plot.typ
  tests/plot/ref.png
  tests/plot/test.typ
Labels: enhancement

#142 Update gallery to 0.1.1
  gallery/3d-chart.typ
  gallery/barchart.png
  gallery/barchart.typ
  gallery/karls-picture.png
  gallery/karls-picture.typ
  gallery/pie-chart.typ
  gallery/plot.typ
  gallery/tree.typ
Labels: documentation

#183 misc: Update to Typst 8 first class types
  .github/workflows/ci.yml
  CHANGES.md
  manual.pdf
  manual.typ
  src/canvas.typ
  src/coordinate.typ
  src/draw.typ
  src/lib/angle.typ
  src/lib/axes.typ
  src/lib/chart.typ
  src/lib/palette.typ
  src/lib/plot.typ
  src/matrix.typ
  src/styles.typ
  src/tree.typ
  src/util.typ
  src/vector.typ
  tests/chart/ref.png
  tests/plot/ref.png
Labels: enhancement

#181 layer: Introduce basic layer/z-index support
  CHANGES.md
  manual.pdf
  manual.typ
  src/canvas.typ
  src/draw.typ
  tests/layer/ref.png
  tests/layer/test.typ
Labels: feature :gift:

#176 plot: Fix formatting of custom tick values
  src/lib/axes.typ
  src/lib/plot.typ
  tests/plot/ref.png
  tests/plot/test.typ
Labels: bug :bug:

#190 Add Catmull-Rom Curve Support
  manual.pdf
  manual.typ
  src/bezier.typ
  src/draw.typ
  src/lib.typ
  src/lib/plot.typ
  src/styles.typ
  tests/catmul/ref.png
  tests/catmul/test.typ
  tests/plot/ref.png
  tests/plot/test.typ
Labels: feature :gift:

#192 draw: Rename catmull k to tension
  manual.pdf
  manual.typ
  src/draw.typ
Labels: enhancement

#193 plot: Add line type support
  manual.pdf
  src/lib/plot.typ
  tests/catmul/ref.png
  tests/catmul/test.typ
  tests/plot/ref.png
  tests/plot/test.typ
Labels: enhancement

#194 plot: Linearization fix
  src/lib/plot.typ
  tests/plot/ref.png
  tests/plot/test.typ
Labels: bug :bug:

#196 draw: Fix rect top/bottom left/right anchors
  src/draw.typ
  tests/rect/ref.png
  tests/rect/test.typ
Labels: bug :bug:

#197 changes: Update changes
  CHANGES.md
Labels: documentation

#198 repo: Rename from typst-canvas to cetz
  manual.pdf
  manual.typ
  typst.toml
Labels: documentation

#200 style: Fix the current styling system
  manual.typ
  src/canvas.typ
  src/lib/angle.typ
  src/lib/axes.typ
  src/styles.typ
  src/util.typ
  tests/angle/ref.png
  tests/angle/test.typ
  tests/arrows/test.typ
  tests/axes/ref.png
  tests/style/ref.png
  tests/style/test.typ
  tests/tree/test.typ
Labels: bug :bug:

#207 doc: Document arc anchor parameter
  manual.pdf
  src/draw.typ
Labels: documentation

#205 script: Fix issues with macOS
  scripts/package
Labels: bug :bug:

#208 tree: Move tree to lib
  manual.pdf
  manual.typ
  src/lib.typ
  src/lib/tree.typ
Labels: documentation, enhancement

#209 aabb: Move bounding box calculation into aabb.typ
  src/aabb.typ
  src/canvas.typ
Labels: enhancement

#213 Fix relative coordinate with `update: false`
  src/coordinate.typ
  tests/relative-no-update/ref.png
  tests/relative-no-update/test.typ
Labels: bug :bug:

#164 Improve mark positioning
  CHANGES.md
  manual.pdf
  manual.typ
  src/bezier.typ
  src/cmd.typ
  src/draw.typ
  src/lib/angle.typ
  src/styles.typ
  tests/angle/ref.png
  tests/arrows/ref.png
  tests/arrows/test.typ
  tests/axes/ref.png
  tests/bezier-through/ref.png
  tests/marks/ref.png
  tests/marks/test.typ
  tests/plot/ref.png
  tests/style/ref.png
  tests/tree/ref.png
Labels: enhancement

#219 draw: Fix content intersection bug
  src/intersection.typ
  tests/intersection/ref.png
  tests/intersection/test.typ
Labels: bug :bug:

#227 feat: add `decorations` library with `brace` function
  manual.pdf
  manual.typ
  src/lib.typ
  src/lib/decorations.typ
  tests/decorations/ref.png
  tests/decorations/test.typ
Labels: feature :gift:

#226 bezier: Fix extrema calculation
  src/bezier.typ
  tests/bounds/ref.png
  tests/bounds/test.typ
  tests/intersection/ref.png
Labels: bug :bug:

#231 plot: Allow plots without data
  src/lib/plot.typ
  tests/plot/ref.png
  tests/plot/test.typ
Labels: bug :bug:, lib:plot
