Repository cetz-package/cetz, pull requests merged in 2023-05, with the labels that each got.

#39 More default anchors
  canvas.typ
  demo/anchor.pdf
  demo/anchor.pdf.png
  demo/anchor.typ
  demo/transform.pdf
  demo/transform.pdf.png
  demo/transform.typ
  manual.pdf
  manual.typ
  tests/image/image.png
  tests/image/ref.png
  tests/image/test.typ
Labels: documentation, enhancement

#44 Draw ellipse/circle using 4 bezier paths
  cmd.typ
  draw.typ
  tests/axes/ref.png
  tests/image/ref.png
  tests/local-anchor/ref.png
  tests/primitives/ref.png
  tests/rotation/ref.png
  tests/translation/ref.png
Labels: enhancement

#45 Add tests for ellipses
  manual.pdf
  manual.typ
  tests/circle/ref.png
  tests/circle/test.typ
Labels: enhancement

#48 Fix an error with the coordinates of the arc.
  cmd.typ
  draw.typ
  tests/local-anchor/test.typ
  tests/primitives/test.typ
  tests/ring/ref.png
Labels: bug

#41 Improve coordinates (#32 and #5)
  canvas.typ
  cmd.typ
  collisions.typ
  coordinate.typ
  demo/3d-diagram.pdf
  demo/3d-diagram.typ
  demo/karl-picture.pdf
  demo/karl-picture.typ
  demo/plot-axes.pdf
  demo/plot-axes.typ
  demo/shadow.pdf
  demo/shadow.typ
  draw.typ
  manual.pdf
  manual.typ
  tests/image/test.typ
  util.typ
Labels: enhancement

#52 Add fill and stroke overrides to draw elements
  cmd.typ
  draw.typ
  manual.pdf
  manual.typ
Labels: enhancement

#51 Use a single transform matrix
  canvas.typ
  draw.typ
  matrix.typ
  util.typ
Labels: enhancement
