Repository cetz-package/cetz, pull requests merged in 2024-01, with the labels that each got.

#427 gallery: Replace 3D-Chart with Waves
  README.md
  gallery/3d-chart.png
  gallery/3d-chart.typ
  gallery/barchart.png
  gallery/waves.png
  gallery/waves.typ
Labels: documentation, enhancement :arrow_up:

#435 plot: Support min/max for add-hline and add-vline
  src/lib/plot.typ
  src/lib/plot/line.typ
Labels: enhancement :arrow_up:, lib:plot

#428 tree: Cleanup + Improvements
  src/lib/tree.typ
  tests/tree/test.typ
Labels: lib:tree

#444 In tree, add "end" and "after-end" as values for parent-position
  src/lib/tree.typ
Labels: bug :bug:, lib:tree

#445 tree: Add tests for parent-position and direction
  .github/workflows/ci.yml
  tests/tree/ref.png
  tests/tree/test.typ
Labels: lib:tree

#416 Mark Improvements
  src/bezier.typ
  src/canvas.typ
  src/draw/shapes.typ
  src/drawable.typ
  src/lib.typ
  src/lib/axes.typ
  src/mark-shapes.typ
  src/mark.typ
  src/matrix.typ
  src/path-util.typ
  src/styles.typ
  src/util.typ
  src/vector.typ
  tests/anchor-on-path/ref.png
  tests/anchor/element-anchors/ref.png
  tests/anchor/element-anchors/test.typ
  tests/anchor/path-anchors/ref.png
  tests/anchor/path-anchors/test.typ
  tests/angle/ref.png
  tests/arc/ref.png
  tests/arrows/ref.png
  tests/bezier-through/ref.png
  tests/bezier-through/test.typ
  tests/bezier/shorten/ref.png
  tests/bezier/shorten/test.typ
  tests/intersection/ref.png
  tests/mark/auto-offset/ref.png
  tests/mark/multiple/ref.png
  tests/mark/multiple/test.typ
  tests/mark/offset/ref.png
  tests/mark/offset/test.typ
  tests/mark/place-marks/ref.png
  tests/mark/place-marks/test.typ
  tests/mark/pos/ref.png
  tests/mark/pos/test.typ
  tests/mark/z-axis/ref.png
  tests/plot/legend/ref.png
  tests/plot/ref.png
  tests/rect/rounded/ref.png
  tests/style/ref.png
  tests/tree/ref.png
  tests/tree/test.typ
Labels: feature :gift:, core:draw :pencil2:, core:styling

#447 Use ratios for lerp coordinates
  CHANGES.md
  gallery/karls-picture.typ
  manual.typ
  src/coordinate.typ
  src/lib/decorations/brace.typ
  src/lib/plot/legend.typ
  tests/coordinate/lerp/ref.png
  tests/coordinate/lerp/test.typ
  tests/image/test.typ
  tests/plot/test.typ
  tests/tree/test.typ
Labels: documentation

#329 Path Decorations
  CHANGES.md
  gallery/karls-picture.typ
  manual.typ
  src/coordinate.typ
  src/drawable.typ
  src/lib/decorations.typ
  src/lib/decorations/brace.typ
  src/lib/decorations/path.typ
  src/lib/plot/legend.typ
  src/mark.typ
  src/util.typ
  tests/anchor-on-path/ref.png
  tests/anchor/copy-anchors/ref.png
  tests/anchor/path-anchors/ref.png
  tests/angle/ref.png
  tests/angle/right-angle/ref.png
  tests/arc/arc-through/ref.png
  tests/arc/ref.png
  tests/bezier/ref.png
  tests/chart/piechart/ref.png
  tests/circle-through/ref.png
  tests/circle/ref.png
  tests/content/intersection/ref.png
  tests/content/ref.png
  tests/content/transform/ref.png
  tests/coordinate/lerp/ref.png
  tests/coordinate/lerp/test.typ
  tests/decorations/path/ref.png
  tests/decorations/path/test.typ
  tests/gradient/ref.png
  tests/group/nested-anchor/ref.png
  tests/image/ref.png
  tests/image/test.typ
  tests/intersection/ref.png
  tests/line/element-element/ref.png
  tests/plot/legend/ref.png
  tests/plot/line/line-type/ref.png
  tests/plot/line/mark/ref.png
  tests/plot/test.typ
  tests/rect/ref.png
  tests/rect/rounded/ref.png
  tests/relative-no-update/ref.png
  tests/rotation/ref.png
  tests/set-get-ctx/ref.png
  tests/translation/ref.png
  tests/tree/test.typ
  tests/viewport/ref.png
Labels: feature :gift:

#380 manual: Some small fixes and improvements
  manual.pdf
  manual.typ
  src/canvas.typ
  src/draw/grouping.typ
  src/draw/shapes.typ
  src/lib/angle.typ
  src/lib/chart.typ
  src/lib/chart/piechart.typ
  src/lib/plot.typ
  src/lib/plot/line.typ
  src/lib/tree.typ
  src/mark.typ
  src/styles.typ
  tests/anchor-on-path/ref.png
  tests/anchor-on-path/test.typ
  tests/hobby/ref.png
  tests/hobby/test.typ
Labels: documentation

#456 repo: Gallery Update
  gallery/karls-picture.png
  gallery/karls-picture.typ
  gallery/tree.png
  gallery/tree.typ
  gallery/waves.typ
Labels: documentation

#460 canvas: Fix RTL documents
  src/canvas.typ
  tests/content/rtl/ref.png
  tests/content/rtl/test.typ
  tests/content/test.typ
Labels: bug :bug:, core:draw :pencil2:

#468 hobby: Fix closed two point hobby curve
  src/hobby.typ
  tests/hobby/ref.png
  tests/hobby/test.typ
Labels: bug :bug:, core:draw :pencil2:

#477 Anchor tidy and fixup
  CHANGES.md
  manual.pdf
  manual.typ
  src/anchor.typ
  src/canvas.typ
  src/draw/grouping.typ
  src/draw/shapes.typ
  src/lib/axes.typ
  src/lib/chart/piechart.typ
  src/lib/decorations/brace.typ
  src/lib/plot.typ
  src/lib/plot/legend.typ
  src/lib/tree.typ
  src/mark.typ
  src/util.typ
  tests/anchor/element-anchors/ref.png
  tests/anchor/element-anchors/test.typ
  tests/anchor/path-anchors/ref.png
  tests/anchor/path-anchors/test.typ
  tests/arc/arc-through/test.typ
  tests/arc/ref.png
  tests/arc/test.typ
  tests/line/element-element/test.typ
Labels: core:draw :pencil2:

#482 lib: Export intersection functions
  src/lib.typ
Labels: bug :bug:

#484 Do not double transform merge path anchors
  src/draw/shapes.typ
  tests/merge/ref.png
  tests/merge/test.typ
Labels: bug :bug:, core:draw :pencil2:
