Repository cetz-package/cetz, pull requests merged in 2024-12, with the labels that each got.

#756 decoration: Allow dynamic amplitudes
  src/lib/decorations.typ
  src/lib/decorations/path.typ
  tests/decorations/path/ref/1.png
  tests/decorations/path/test.typ
Labels: feature :gift:

#767 decoration: Allow specifying amplitudes as lengths
  src/lib/decorations/path.typ
  tests/decorations/path/ref/1.png
  tests/decorations/path/test.typ
Labels: enhancement :arrow_up:

#764 gallery: Add Icosahedron Example
  README.md
  gallery/paciolis.png
  gallery/paciolis.typ
  gallery/tree.typ
Labels: documentation
