Repository cetz-package/cetz, pull requests merged in 2024-11, with the labels that each got.

#745 Add `chronos`, `circuiteria` and `rivet` to projects
  README.md
Labels: documentation

#733 docs: Add mark `anchor` documentation
  docs/basics/marks.mdx
Labels: documentation

#759 intersection: Provide sort functions
  src/draw/grouping.typ
  src/lib.typ
  src/sorting.typ
  tests/intersection/ref/1.png
  tests/intersection/test.typ
Labels: feature :gift:

#744 hobby: Set omega to 0
  src/styles.typ
  tests/decorations/path/ref/1.png
  tests/mark/auto-offset/ref/1.png
  tests/mark/multiple/ref/1.png
Labels: core:styling

#743 angle: Resolve radius
  src/lib/angle.typ
  tests/angle/ref/1.png
  tests/angle/test.typ
Labels: bug :bug:

#754 content: Bring back implicit frame
  src/draw/shapes.typ
  tests/content/intersection/ref/1.png
  tests/content/intersection/test.typ
  tests/content/ref/1.png
  tests/content/test.typ
  tests/line/element-element/ref/1.png
Labels: bug :bug:
