Repository cetz-package/cetz, pull requests merged in 2025-03, with the labels that each got.

#820 treewide: Release 0.3.3
  CHANGES.md
  README.md
  docs/advanced/custom-types.mdx
  docs/getting-started.mdx
  docs/tutorials/karl.mdx
  gallery/karls-picture.png
  gallery/karls-picture.typ
  gallery/paciolis.png
  gallery/paciolis.typ
  gallery/periodic-table.png
  gallery/periodic-table.typ
  gallery/plate-capacitor.png
  gallery/plate-capacitor.typ
  gallery/tree.typ
  gallery/waves.png
  gallery/waves.typ
  src/anchor.typ
  src/bezier.typ
  src/canvas.typ
  src/draw/projection.typ
  src/draw/transformations.typ
  src/mark.typ
  src/matrix.typ
  src/version.typ
  tests/mark-style/ref/1.png
  tests/mark-style/test.typ
  typst.toml
Labels: bug :bug:, enhancement :arrow_up:

#832 canvas: Fix Curve Rendering with Typst 0.13.1
  .github/workflows/ci.yml
  CHANGES.md
  README.md
  docs/getting-started.mdx
  docs/tutorials/karl.mdx
  gallery/karls-picture.typ
  gallery/paciolis.typ
  gallery/periodic-table.typ
  gallery/plate-capacitor.typ
  gallery/tree.typ
  gallery/waves.typ
  src/canvas.typ
  tests/anchor-centroid/ref/1.png
  tests/angle/ref/1.png
  tests/arrows/ref/1.png
  tests/circle-through/ref/1.png
  tests/content-intersection/ref/1.png
  tests/content-padding/ref/1.png
  tests/content-rtl/ref/1.png
  tests/content-span/ref/1.png
  tests/content/ref/1.png
  tests/cube/ref/1.png
  tests/gradient/ref/1.png
  tests/intersection/ref/1.png
  tests/line-element-element-intersection/ref/1.png
  tests/line-fill-rule/ref/1.png
  tests/mark-anchors/ref/1.png
  tests/mark-auto-offset/ref/1.png
  tests/mark-position/ref/1.png
  tests/mark-shape-transform/ref/1.png
  tests/mark-single/ref/1.png
  tests/mark-style/ref/1.png
  tests/mark-z-axis/ref/1.png
  tests/merge/ref/1.png
  tests/multiple-marks/ref/1.png
  tests/polygon/ref/1.png
  tests/projection-default/ref/1.png
  tests/projection-ortho/ref/1.png
  tests/rect-rounded/ref/1.png
  tests/rotate-around/ref/1.png
  tests/set-get-ctx/ref/1.png
  tests/style/ref/1.png
  tests/tree/ref/1.png
  typst.toml
Labels: bug :bug:

#834 Typst 0.13.1 fixes
  src/canvas.typ
  src/mark.typ
  tests/anchor-centroid/ref/1.png
  tests/angle/ref/1.png
  tests/arrows/ref/1.png
  tests/arrows/test.typ
  tests/circle-through/ref/1.png
  tests/content-intersection/ref/1.png
  tests/content-padding/ref/1.png
  tests/content-rtl/ref/1.png
  tests/content-span/ref/1.png
  tests/content/ref/1.png
  tests/cube/ref/1.png
  tests/gradient/ref/1.png
  tests/intersection/ref/1.png
  tests/line-element-element-intersection/ref/1.png
  tests/line-fill-rule/ref/1.png
  tests/mark-anchors/ref/1.png
  tests/mark-auto-offset/ref/1.png
  tests/mark-position/ref/1.png
  tests/mark-shape-transform/ref/1.png
  tests/mark-single/ref/1.png
  tests/mark-style/ref/1.png
  tests/mark-z-axis/ref/1.png
  tests/merge/ref/1.png
  tests/multiple-marks/ref/1.png
  tests/polygon/ref/1.png
  tests/projection-default/ref/1.png
  tests/projection-ortho/ref/1.png
  tests/rect-rounded/ref/1.png
  tests/rotate-around/ref/1.png
  tests/set-get-ctx/ref/1.png
  tests/style/ref/1.png
  tests/tree/ref/1.png
Labels: bug :bug:

#844 Add fast path for rect without radius
  .gitignore
  src/draw/shapes.typ
Labels: enhancement :arrow_up:
