Repository cetz-package/cetz, pull requests merged in 2025-01, with the labels that each got.

#780 Replace the URL in the submodule with read-only URL
  .gitmodules
Labels: bug :bug:

#783 Add `gallery/periodic-table.{typ,png}`
  gallery/periodic-table.png
  gallery/periodic-table.typ
Labels: documentation

#784 Include Periodic Table in Readme
  README.md
Labels: documentation

#775 group: Add anchor test
  tests/group/anchors/ref/1.png
  tests/group/anchors/test.typ
Labels: enhancement :arrow_up:

#782 treewide: Prepare for upcomming typst version
  src/coordinate.typ
  src/deps.typ
  src/path-util.typ
Labels: bug :bug:

#785 waves: Use ortho function
  gallery/waves.png
  gallery/waves.typ
Labels: documentation

#774 bezier: Fix bezier through control points
  src/bezier.typ
  tests/bezier-through/ref/1.png
  tests/bezier-through/test.typ
Labels: bug :bug:

#771 flat-brace: Add missing stroke & fill keys
  src/lib/decorations/brace.typ
  tests/decorations/ref/1.png
  tests/decorations/test.typ
Labels: bug :bug:

#781 tree: Add parameters for specifying the node layer
  src/lib/tree.typ
  tests/tree/ref/1.png
  tests/tree/test.typ
Labels: enhancement :arrow_up:

#765 vector: Add element-product function
  src/vector.typ
Labels: feature :gift:

#777 shapes: Add polygon shape
  src/draw.typ
  src/draw/shapes.typ
  src/styles.typ
  tests/polygon/ref/1.png
  tests/polygon/test.typ
Labels: feature :gift:

#778 line: Add default anchor for closed lines
  src/draw/shapes.typ
Labels: bug :bug:

#797 fix typo coordinate-systems.mdx
  docs/basics/coordinate-systems.mdx
Labels: documentation

#799 Content Auto-Scaling
  src/draw/shapes.typ
  src/styles.typ
  tests/content/ref/1.png
  tests/content/test.typ
Labels: feature :gift:

#791 treewide: Version + Changelog
  CHANGES.md
  README.md
  docs/getting-started.mdx
  docs/tutorials/karl.mdx
  gallery/karls-picture.typ
  gallery/paciolis.typ
  gallery/periodic-table.typ
  gallery/plate-capacitor.typ
  gallery/tree.typ
  gallery/waves.typ
  typst.toml
Labels: documentation

#801 doc: Fix tangent example
  docs/basics/coordinate-systems.mdx
Labels: documentation

#803 docs: Update documentation
  docs/api/draw-functions/shapes/polygon.mdx
  docs/api/draw-functions/shapes/shapes.md
  docs/api/sidebar.js
  src/draw/shapes.typ
Labels: documentation
